FROM python:3.12-slim

RUN pip install uv

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync

RUN uv run playwright install chromium
RUN uv run playwright install-deps chromium

COPY . .

CMD ["uv", "run", "python", "app.py"]